#!/usr/bin/bash
# convert cbr (rar) to cbz (zip)
# by klaatu
VERSION=0.2
####
# DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#                   Version 2, December 2004
#
# Copyright (C) 2004 Sam Hocevar <sam@hocevar.net>
#
# Everyone is permitted to copy and distribute verbatim or modified
# copies of this license document, and changing it is allowed as long
# as the name is changed.
#
#           DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#  TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
#
# 0. You just DO WHAT THE FUCK YOU WANT TO.
####

help() {
    ## this function provides help if the user clearly does
    ## not know how to use the application

    echo "cbr2cbz <OPTIONS> FILENAME.cbr OR DIRECTORY"
    echo ""
}

version_return() {
    ## this function pings the website to check current version
    ## and alerts the user if an upgrade is available

    # echo "Checking for upgrade..."
    # UPGRADE=$(curl --connect-timeout 10 -s slackermedia.info/sport/index.html | grep VERSIONCHECK= | cut -f2 -d"=" )

    # if [ "X$VERSION" != "X$UPGRADE" ]; then
	# echo "An upgrade of Slackport is available."
    # else
	echo "$VERSION"
    #fi

    echo ""
}


while [ True ]; do
if [ "$1" = "help" -o "$1" = "--help" -o "$1" = "-h" -o "$1" = "" ]; then 
    help
    shift 1
#elif [ "$1" = "install" -o "$1" = "--install" -o "$1" = "-i" -o "$1" = "i" ]; then 
#    MODE=installmode
#    INSTALLER=${INSTALLER:-installpkg}
#    shift 1
elif [ "$1" = "version" -o "$1" = "--version" -o "$1" = "-v" -o "$1" = "v" ]; then     
    echo "cbr2cbz version "
    version_return
    shift 1
else
    break
fi
done

# everything else left at this point
# SHOULD be a package name, so..
# build an array of packages
ARG="${@}"
set -e 

FILENAM="$(basename "${ARG}" .cbr)"
echo "${FILENAM}"

CWD=$(pwd)

mkdir cbr2tmp || exit 1
echo "${ARG}"
7z e "${ARG}" -ocbr2tmp
pushd cbr2tmp
zip "${FILENAM}.cbz" *
echo "${FILENAM}.cbz created"
mv -v "${FILENAM}.cbz" $CWD
popd

rm -rf cbr2tmp
echo "Conversion Complete."
